import "./globals.css";
import Link from "next/link";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const header = (
    <header className="bg-slate-600 mx-10 my-5 rounded-lg px-1 py-2">
      <div className="flex justify-start divide-x-2 divide-blue-300">
        <Link href="/">
          <p className="font-bold text-white pl-5 px-5">F Inc</p>
        </Link>

        <Link href="/posts">
          <p className="font-bold text-white pl-5 px-5">Posts</p>
        </Link>

        <Link href="/generate">
          <p className="font-bold text-white pl-5 px-5">Submit new post</p>
        </Link>
      </div>
    </header>
  );

  return (
    <html lang="en">
      <body>
        <div className="mb-10">{header}</div>


          {children}

      </body>
    </html>
  );
}
